### ISSUE TITLE
does MinimalWebView.exe.WebView2 need install Edge or Any [WebView2 RunTime] ?

### ISSUE THREAD

**Issue by sgf** [rgwood/MinimalWebView#6]
does MinimalWebView.exe.WebView2 need install Edge or Any [WebView2 RunTime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) ?

**Comment by rgwood** [comment]
Yes, it uses WebView2 so it needs a WebView2 runtime installed.
